# Generated by Django 6.0 on 2026-01-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=100)),
                ("open_ports", models.TextField(blank=True)),
                ("risk_score", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ScanLog",
        ),
        migrations.AlterField(
            model_name="otpstore",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
