# Generated by Django 6.0 on 2026-02-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_scanresult_delete_scanlog_alter_otpstore_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPStore",
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="risk_score",
            field=models.IntegerField(),
        ),
    ]
